# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3

pipelines:
  default:
    
    - step:
        name: 'Build'
        script:
          - apt-get -y update
          - apt-get -y install git
          - git archive master --format=tar.gz --output=sample-app.tar.gz
        artifacts: 
          - sample-app.tar.gz

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    
    - step:
        name: 'Deployment'
        deployment: production
        trigger: 'manual'
        caches: 
          - pip
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: 'sample-app.tar.gz'
    