# Generated by Django 3.2.3 on 2021-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petroleum_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('petroleum_product', models.CharField(max_length=100)),
                ('sale', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Datum',
            },
        ),
    ]
